# Generated by Django 3.2 on 2021-07-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Vacancies'},
        ),
        migrations.AlterField(
            model_name='error',
            name='timestamp',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='timestamp',
            field=models.DateField(auto_now=True, verbose_name='Add time'),
        ),
    ]
